language: java
jdk:
- openjdk11
sudo: false
env:
  global:
  - secure: bz7jnorOC9afY1D1V0huPPZo1DuqUyo42LeBbIiWgc8PICYlnh9JHlKovUmAGdfSEGAa+hQLGPV6PEwdv1a1hi4VZmvDd0WG76HdMb2ZjKt3rq0g0MXdOOdW/rCEXPi42RgRP3XMH+2nDvtnTNNSRBVGOaKNh1c2HMYXKoDEWIPXn6PVQSfVpT4Iu/OSkrMcF24xMDHb23cpl+xCDXml9RMNQY7a6bic8437Fq8fjyc5h7xAT7CNJScypJojVdnqlxq/OnGVaitrEm368i5FdOm8G6vqbTn/kpv42XfwqVLl8Lw/zAnwyNNEYoyODN1qsUVE73zfvL/lMpxhySd8l99/RnA93xWhehkISaxl7fBnQSZIgPnXlbobsDZsuhqT4giDVqbt5N4Z7124LufCVjEU1XDjgFzLzfICnB+f2HD5J7yzTeVGNz4VnwdkcTy80ig7mXTGZAxZf39zKaT1F0j5IaMVuCIoR59/k7sKV678qmywlpI8YgddcrNPw82HCFa9r5TnWv3yXwCHB2YwJB67R2He0UMhSLe/dlqVcieo/Wsa4AUYFT1U3l6A+iO2UcCxVtSZWYDMPm+YuD+shO7FWtxGoqfoLpZSgzIqKiRef9DXY11Bk1nXMht68q+siZ3sCqCo+M1TESZSUTC/cP9Lj3gByaEfqLpUHXzxT7k=
before_install:
- openssl aes-256-cbc -K $encrypted_7373d903a788_key -iv $encrypted_7373d903a788_iv
  -in codesigning.asc.enc -out codesigning.asc -d
- gpg --fast-import codesigning.asc
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V --quiet
script: 
cache:
  directories:
  - "$HOME/.m2/repository"
deploy:
- provider: script
  script: mvn deploy -DskipTests --quiet --settings mvn-settings.xml
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
    condition: $(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}'
      --non-recursive exec:exec)  = *"SNAPSHOT"*
- provider: script
  script: mvn deploy -DskipTests --quiet --settings mvn-settings.xml
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^ams-v"
