name:  Ant Media Server Parent Test

on:
  push:
    branches:
      - '**'
    tags:
      - 'ams-v*'
  pull_request:
    branches:
      - '**'

jobs:
  run-test:
    runs-on: ubuntu-22.04
    container: maven:3.9.16-eclipse-temurin-17

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache Maven repository
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build Ant Media Server Parent project
        run: |
          mvn -version
          mvn install -Dgpg.skip=true -B -V

  deploy:
    runs-on: ubuntu-22.04
    container: maven:3.9.16-eclipse-temurin-17
    needs: run-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache Maven repository
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --yes --import
          gpg --list-keys

      - name: Deploy
        run: mvn deploy -DskipTests -Dgpg.batch=true --quiet --settings mvn-settings.xml
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

