name:  Ant Media Server Parent Test

on:
  push:
    branches:
      - '**'
    tags:
      - 'ams-v*'
  pull_request:
    branches:
      - '**'

jobs:
  run-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
            
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - run: sudo apt-get update -qq
      - run: sudo apt-get install ffmpeg -qq -y

      - name: Build Ant Media Server Parent project
        run: |
          ls -alh
          mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V --quiet
          cd ..

  deploy:
    runs-on: ubuntu-22.04
    needs: run-test
    env:
      GPG_TTY: $(tty)
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --yes --import
          gpg --list-keys

      - name: Deploy
        run: mvn deploy -DskipTests -Dgpg.batch=true --quiet --settings mvn-settings.xml
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}


